CREATE TABLE PAYMENTS(
  order_id VARCHAR(255) PRIMARY KEY,
  pay_type VARCHAR(255),
  amount FLOAT,
  pay_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES ORDERS(order_id)
);